src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TacheRepository::class)
 */
class Tache
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="taches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Priorite;

    /**
     * @ORM\ManyToOne(targetEntity=Priorite::class, inversedBy="taches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Propriete;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPriorite(): ?string
    {
        return $this->Priorite;
    }

    public function setPriorite(string $Priorite): self
    {
        $this->Priorite = $Priorite;

        return $this;
    }

    public function getPropriete(): ?Priorite
    {
        return $this->Propriete;
    }

    public function setPropriete(?Priorite $Propriete): self
    {
        $this->Propriete = $Propriete;

        return $this;
    }
}

src/Controller/TacheControlleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TacheControlleController extends AbstractController
{
    /**
     * @Route("/listeTaches", name="listeTaches")
     */
    public function index(): Response
    {
        return $this->render('tache_controlle/index.html.twig', [
            'controller_name' => 'TacheControlleController',
        ]);
    }
    /**
    * @Route("/supprTache/{id}",name="supprTache")
    */
    public function supprTache(EntityManagerInterface $manager,Utilisateur $editutil): Response 
    {
    $manager->remove($editutil);
    $manager->flush();
    // Affiche de nouveau la liste des utilisateurs
    return $this->redirectToRoute ('listeTaches');
    }
}

templates/tache_controlle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}📌Liste des taches📌{% endblock %}

{% block body %}
<center>
<h1>📌 Liste des taches 📌</h1>
</center>
<br>
<br>
<table class="table table-info">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Date</th>
      <th scope="col">Priorite</th>
    </tr>
  </thead>
  <tbody>
{% for une_tache in lst_tache %}
    <tr class="table-active">
      <td>{{ une_tache.description }} </td>
      <td>{{ une_tache.date }}</td>
      <td>{{ une_tache.priorite }}</td>
      <td><a href="/supprTache/{{ une_date.id }}"> <input type="button" class="btn btn-danger" value="Supprimer"> </a></td>
    </tr>
  </tbody>
  {% endfor %}
</table>

{% endblock %}